name: Release CSM
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
jobs:
  build-and-scan:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Release version and branch name
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "branch_name=release-v${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Validate version input
        run: |
          if [[ "$version" == "none" ]]; then
            echo "Invalid version specified: $version Must follow major, minor, patch versioning."
            exit 1
          fi
        env:
          version: ${{ env.version }}

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.branch_name }}
          fetch-depth: 0

#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: "1.23"

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Verify if release branch exists
        run: |
          echo "Checking if release branch '${{ env.branch_name }}' exists..."
          git fetch --all
          echo "Listing all remote branches..."
          git branch -r
          if git branch -r | grep "origin/${{ env.branch_name }}"; then
            echo "The branch ${{ env.branch_name }} exists."
          else
            echo "The branch ${{ env.branch_name }} does not exist."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify branch changes
        run: |
          changes_made=false
          if git diff --quiet origin/main origin/${{ env.branch_name }}; then
            echo "No changes detected between ${{ env.branch_name }} and main. Aborting.."
            echo "changes_made=false" >> $GITHUB_ENV
            exit 1
          else
            echo "Changes detected. Proceeding for PR creation"
            echo "changes_made=true" >> $GITHUB_ENV
          fi

          echo "Commit log of ${{ env.branch_name }} compared to main:"
          git log origin/main..origin/${{ env.branch_name }} --oneline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Pull Request Template
        run: |
          echo "### Release Notes" > pull_request_template.md
          echo "Description: Release v${{ env.version }}" >> pull_request_template.md
          echo "" >> pull_request_template.md

      # Create a Pull Request using GitHub CLI
      - name: Create Pull Request using GitHub CLI
        run: |
          echo "# Description" > temp_release_pr_body.md
          echo "Release v1.12.0" >> temp_release_pr_body.md
          echo "" >> temp_release_pr_body.md
          tail -n +2 pull_request_template.md >> temp_release_pr_body.md
          gh pr create --title "Release v${{ env.version }}" \
                       --body "Release v${{ env.version }}" \
                       --template "temp_release_pr_body.md" \
                       --base main \
                       --head ${{ env.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Wait for PR to be merged
        if: env.changes_made == 'true'
        run: |
          echo "Waiting for the PR to be merged. Please merge the PR manually."
          timeout=60  # Timeout in minutes
          while [ $timeout -gt 0 ]; do
            pr_status=$(gh pr view "Release v${{ env.version }}" --json state --jq '.state')
            if [ "$pr_status" = "MERGED" ]; then
              echo "PR has been merged."
              break
            fi
            echo "PR not merged yet. Sleeping for 1 minute..."
            sleep 60
            timeout=$((timeout - 1))
          done
          if [ $timeout -eq 0 ]; then
            echo "Timeout reached. PR was not merged."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        run: |
          git fetch --tags
          git tag v${{ env.version }}
          git push origin v${{ env.version }}

      - name: Create Release
        id: release_notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: Release v${{ env.version }}
          draft: true
          prerelease: false
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach Built Binaries
        run: |
          gh release upload "v${{ env.version }}" csm/releases/download/v${{ env.version }}/dellctl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
